Description: Pattern with packages for tucana configurations
Name: jolla-configuration-tucana
Requires:
- patterns-sailfish-device-configuration-tucana

Summary: Jolla Configuration tucana
Description: Pattern with packages for tucana configurations
Name: jolla-configuration-tucana
Requires:
- patterns-sailfish-device-configuration-tucana

Summary: Jolla Configuration tucana
